# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/commander.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1263, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_label.sizePolicy().hasHeightForWidth())
        self.mode_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mode_label.setFont(font)
        self.mode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_label.setObjectName("mode_label")
        self.verticalLayout.addWidget(self.mode_label)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.takeoff_button = QtWidgets.QPushButton(self.centralwidget)
        self.takeoff_button.setObjectName("takeoff_button")
        self.horizontalLayout.addWidget(self.takeoff_button)
        self.idle_button = QtWidgets.QPushButton(self.centralwidget)
        self.idle_button.setObjectName("idle_button")
        self.horizontalLayout.addWidget(self.idle_button)
        self.land_button = QtWidgets.QPushButton(self.centralwidget)
        self.land_button.setObjectName("land_button")
        self.horizontalLayout.addWidget(self.land_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.distance_slider = QtWidgets.QSlider(self.centralwidget)
        self.distance_slider.setMinimum(10)
        self.distance_slider.setMaximum(300)
        self.distance_slider.setProperty("value", 30)
        self.distance_slider.setOrientation(QtCore.Qt.Horizontal)
        self.distance_slider.setObjectName("distance_slider")
        self.horizontalLayout_2.addWidget(self.distance_slider)
        self.distance_label = QtWidgets.QLabel(self.centralwidget)
        self.distance_label.setObjectName("distance_label")
        self.horizontalLayout_2.addWidget(self.distance_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.limit_slider = QtWidgets.QSlider(self.centralwidget)
        self.limit_slider.setMinimum(10)
        self.limit_slider.setMaximum(300)
        self.limit_slider.setProperty("value", 160)
        self.limit_slider.setOrientation(QtCore.Qt.Horizontal)
        self.limit_slider.setObjectName("limit_slider")
        self.horizontalLayout_4.addWidget(self.limit_slider)
        self.limit_label = QtWidgets.QLabel(self.centralwidget)
        self.limit_label.setObjectName("limit_label")
        self.horizontalLayout_4.addWidget(self.limit_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.mire_display = MireDisplay(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mire_display.sizePolicy().hasHeightForWidth())
        self.mire_display.setSizePolicy(sizePolicy)
        self.mire_display.setMinimumSize(QtCore.QSize(968, 608))
        self.mire_display.setObjectName("mire_display")
        self.horizontalLayout_3.addWidget(self.mire_display)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CX10 commander"))
        self.mode_label.setText(_translate("MainWindow", "MANU"))
        self.takeoff_button.setText(_translate("MainWindow", "Take Off"))
        self.idle_button.setText(_translate("MainWindow", "IDLE"))
        self.land_button.setText(_translate("MainWindow", "Land"))
        self.label_2.setText(_translate("MainWindow", "distance"))
        self.distance_label.setText(_translate("MainWindow", "3.0"))
        self.start_button.setText(_translate("MainWindow", "start mission"))
        self.label_3.setText(_translate("MainWindow", "Limit"))
        self.limit_label.setText(_translate("MainWindow", "16.0"))

from miredisplay import MireDisplay
